In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
dataset = pd.read_csv("Andbrain_DataSet.csv")
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -1].values

In [18]:
print(x)

[[0.04783164 0.00063776]
 [0.00018239 0.0004086 ]
 [0.00017724 0.00017724]
 ...
 [0.02800325 0.00040584]
 [0.03333333 0.00476191]
 [0.05357143 0.01785714]]


In [19]:
print(y)

[0.04017858 0.00018647 0.00265863 ... 0.0239448  0.05238096 0.01785714]


In [21]:
!pip install matplotlib-venn

In [22]:
!apt-get -qq install -y libfluidsynth1

Selecting previously unselected package libfluidsynth1:amd64.
(Reading database ... 156210 files and directories currently installed.)
Preparing to unpack .../libfluidsynth1_1.1.9-1_amd64.deb ...
Unpacking libfluidsynth1:amd64 (1.1.9-1) ...
Setting up libfluidsynth1:amd64 (1.1.9-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link



In [25]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

Selecting previously unselected package libarchive-dev:amd64.
(Reading database ... 156215 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.2.2-3.1ubuntu0.7_amd64.deb ...
Unpacking libarchive-dev:amd64 (3.2.2-3.1ubuntu0.7) ...
Setting up libarchive-dev:amd64 (3.2.2-3.1ubuntu0.7) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
     |████████████████████████████████| 154 kB 3.5 MB/s 
  Created wheel for libarchive: filename=libarchive-0.4.7-py3-none-any.whl size=31646 sha256=c3cbb28229b0ecbdbf04e73397dcab0e5cc6fefe99837c313f1a65e39fcdd640
  Stored in directory: /root/.cache/pip/wheels/63/b1/c6/b3da79bec2012175bd43603eed98ef8548ac1733b77c1d4330
Successfully built libarchive


In [26]:
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

In [27]:
!pip install cartopy
import cartopy

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0 )

In [31]:
print(x_train)

[[2.3809526e-02 2.3809526e-02]
 [1.5664162e-05 1.2562657e-03]
 [3.0612247e-02 1.0204082e-02]
 ...
 [2.5510205e-02 5.1020410e-03]
 [1.6544957e-04 4.5755363e-04]
 [5.9523810e-02 1.1904763e-02]]


In [32]:
print(x_test)

[[1.00424340e-02 1.41442720e-04]
 [2.38095260e-02 2.38095260e-02]
 [3.26278660e-02 8.81834250e-04]
 [2.33516490e-02 1.37362650e-03]
 [7.14285750e-02 6.49350700e-03]
 [5.56805430e-02 5.62429700e-04]
 [7.70160100e-03 1.51011790e-04]
 [3.51864900e-06 1.41097830e-03]
 [1.51098910e-02 1.37362650e-03]
 [3.73015900e-02 7.93650860e-04]
 [8.73015900e-02 7.93650800e-03]
 [2.14285740e-02 7.14285760e-03]
 [2.38095260e-02 2.38095260e-02]
 [7.74932650e-03 3.36927250e-04]
 [2.04968940e-02 2.07039350e-04]
 [1.89778860e-04 5.99222960e-04]
 [1.20530670e-02 3.24381180e-02]
 [5.35714330e-02 1.78571440e-02]
 [1.07142866e-01 3.57142870e-02]
 [3.57142870e-02 3.57142870e-02]
 [3.57142870e-02 3.57142870e-02]
 [5.95238100e-02 1.19047630e-02]
 [2.11370250e-02 7.28863000e-04]
 [3.57142870e-02 1.19047630e-02]
 [4.16666680e-02 5.95238150e-03]
 [3.57142870e-02 3.96825400e-03]
 [1.22336230e-02 3.94633000e-04]
 [2.38095260e-02 2.38095260e-02]
 [2.67857160e-02 8.92857200e-03]
 [7.05815900e-05 1.13212890e-03]
 [4.482263

In [33]:
print(y_train)

[7.14285750e-02 9.39849600e-06 3.06122470e-02 4.28571480e-02
 5.78231330e-02 1.88431220e-02 2.94117670e-02 3.57142870e-02
 5.95238100e-02 3.13852840e-02 5.35714330e-02 1.11997230e-01
 7.14285750e-02 1.04958900e-01 6.04395640e-02 1.02040820e-02
 1.06861650e-02 4.20918400e-02 2.70935970e-02 5.35714330e-02
 8.57142900e-03 2.55102050e-02 2.97619050e-02 2.15146320e-02
 1.78571440e-02 1.28534700e-05 2.67857160e-02 2.67857160e-02
 4.63821930e-03 3.60824730e-02 1.00000000e-01 5.00000000e-02
 5.84415600e-02 5.35714330e-02 2.39448040e-02 7.73809550e-02
 7.16456800e-03 1.44557830e-02 3.57142870e-02 5.95238100e-02
 1.78571440e-02 3.57142870e-02 1.78571440e-02 3.57142870e-02
 4.18719240e-02 2.08333340e-02 3.06122470e-02 1.19047630e-02
 8.58250300e-05 2.07373280e-02 8.87672100e-03 4.16666680e-02
 4.21245470e-02 1.83463810e-04 5.95238100e-02 2.42182720e-02
 2.70935970e-02 3.24675370e-02 1.07033644e-04 7.14285750e-02
 4.28571480e-02 1.83673480e-02 1.02040820e-02 2.55102050e-02
 2.38095260e-02 4.761905

In [34]:
print(y_test)

[6.93069300e-03 2.38095260e-02 2.02821880e-02 3.15934100e-02
 6.49350700e-03 3.31833500e-02 4.37934200e-03 3.51864900e-06
 5.08241770e-02 1.82539700e-02 2.38095260e-02 3.57142870e-02
 7.14285750e-02 6.40161750e-03 2.04968940e-02 1.86790190e-04
 1.07587770e-02 1.78571440e-02 3.57142870e-02 1.07142866e-01
 1.07142866e-01 5.95238100e-02 2.40524780e-02 1.19047630e-02
 4.16666680e-02 1.98412720e-02 9.07656000e-03 2.38095260e-02
 2.67857160e-02 7.05815900e-05 2.32502400e-02 2.31092460e-02
 2.48618800e-04 1.73745200e-02 3.62244920e-02 4.28571480e-02
 3.57142870e-02 1.85714290e-02 3.05299550e-02 5.95238150e-03
 2.67857160e-02 3.44611560e-02 1.42857150e-02 3.57142870e-02
 8.66158160e-02 1.19047630e-02 2.27021050e-02 5.33794200e-02
 1.19047630e-02 2.55102050e-02 3.57142870e-02 2.67857160e-02
 2.74725300e-02 4.11051300e-02 1.78571440e-02 1.20748304e-01
 2.35562300e-02 1.02040820e-02 2.22619070e-04 1.42857150e-02
 3.94736830e-02 3.09168450e-02 3.91705100e-02 5.95238100e-02
 7.14285750e-02 2.067669

In [37]:
!pip install matplotlib-venn

In [38]:
!apt-get -qq install -y libfluidsynth1

In [39]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

In [40]:
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

In [41]:
!pip install cartopy
import cartopy

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [45]:
print(x_train)

[[-0.33504066  1.54237602]
 [-1.31439937 -0.6971123 ]
 [-0.0550397   0.19138585]
 ...
 [-0.26504047 -0.31523542]
 [-1.30823418 -0.77642263]
 [ 1.13496431  0.36025967]]


In [46]:
print(x_test)

[[-0.90169611 -0.80781173]
 [-0.33504066  1.54237602]
 [ 0.02792346 -0.73429251]
 [-0.35388694 -0.68545864]
 [ 1.62496611 -0.17706595]
 [ 0.9767749  -0.76600867]
 [-0.99804512 -0.80686155]
 [-1.31489928 -0.68174969]
 [-0.69311886 -0.68545864]
 [ 0.2202946  -0.74304892]
 [ 2.27830165 -0.03377918]
 [-0.43304098 -0.11258689]
 [-0.33504066  1.54237602]
 [-0.99608073 -0.78840056]
 [-0.47138906 -0.80129813]
 [-1.30723278 -0.76235518]
 [-0.81893817  2.39917591]
 [ 0.88996363  0.95131779]
 [ 3.09497137  2.72449216]
 [ 0.15496098  2.72449216]
 [ 0.15496098  2.72449216]
 [ 1.13496431  0.36025967]
 [-0.44504118 -0.74948221]
 [ 0.15496098  0.36025967]
 [ 0.39996182 -0.23079851]
 [ 0.15496098 -0.42781793]
 [-0.81150646 -0.7826705 ]
 [-0.33504066  1.54237602]
 [-0.21254026  0.06473056]
 [-1.31213896 -0.70943881]
 [ 0.52986167 -0.79805568]
 [ 0.55849184 -0.75232042]
 [-1.30405291 -0.76947782]
 [-0.75882592 -0.63016215]
 [-0.62204168 -0.77119455]
 [-0.72704206  0.59668288]
 [ 0.15496098  2.72449216]
 

In [49]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

ValueError: ignored

In [50]:
y_pred = classifier.predict(x_test)

AttributeError: ignored